<?php

// This file was generated by running "composer dump-env dev"

$dev = array(
    'APP_ENV' => 'dev',
    'APP_SECRET' => 'bc4248cda4787faab619d270be8594aa',
    'APP_DEBUG' => '0',
    'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/nayi-kino?serverVersion=8&charset=utf8mb4',
//    'DATABASE_URL' => 'mysql://if0_39161004:fuTVNumW2pwfyFD@sql302.infinityfree.com:3306/if0_39161004_nayi_film?serverVersion=8&charset=utf8mb4',
);

$prod = array(
    'APP_ENV' => 'prod',
    'APP_SECRET' => 'bc4248cda4787faab619d270be8594aa',
    'APP_DEBUG' => '1',
    'DATABASE_URL' => 'mysql://if0_39161004:fuTVNumW2pwfyFD@sql302.infinityfree.com:3306/if0_39161004_nayi_film?serverVersion=8&charset=utf8mb4',
);

//return $dev;
return $prod;