<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'bc4248cda4787faab619d270be8594aa',
  'APP_DEBUG' => '0',
  'DATABASE_URL' => 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=15&charset=utf8',
);



//return array (
//    'APP_ENV' => 'prod',
//    'APP_SECRET' => 'bc4248cda4787faab619d270be8594aa',
//    'APP_DEBUG' => '1',
//    'DATABASE_URL' => 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=15&charset=utf8',
//);
